version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  server:
    restart: on-failure
    build: ./server
    depends_on:
      - redis
    ports:
      - '81:8000'
  nginx:
    build: ./nginx
    ports:
      - '7000:80'
    depends_on:
      - server
